[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


remappings = [
    "@layerzerolabs/solidity-examples/=lib/solidity-examples/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap/v2-core/contracts=lib/v2-core/contracts",
    "@uniswap/v3-core/contracts=lib/v3-core/contracts",
    "@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts",
]