[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 800

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


remappings = [
    "@layerzerolabs/solidity-examples/=lib/solidity-examples/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
